Create Homepage (Including NavBar)
acmucsd-projects/fa2024-hack-team-2 pull request #44
Opened 2024-12-27 01:50 UTC by OrigamiStarz

Notes:
- User can swipe left/right to indicate disinterest/interest
- User can tap on the cards to switch between cards
- NavBar is not connected to other components like the History Component yet
- Some use of normal CSS styling instead of Tailwind since it was easier to write/use normal CSS styling when variables were present

Some future considerations to add to homepage:
- [ ] Swiping up/down to switch photos
- [ ] Cards returning to normal position more smoothly after being swiped 
- [ ] Making the swipe left/right more efficient
- [ ] Making the tap not trigger when user fully swipes on the cards
- [ ] Idle animations for tapping/swiping (i.e. should trigger when user is idle, telling the user to tap or swipe)

2024-12-27 08:03 UTC, crebollarramirez commented
Great job on the navbar! Everything is looking fantastic. Just a couple of things to refine:  

1. Adjust the vertical alignment of both the left and right components so they are centered.  
2. Slightly increase the size of the left component to enhance the styling.  

The Figma design serves as an excellent reference, but it's perfectly fine if it doesn’t match it exactly.  

Let me know if you have any questions!

2024-12-27 08:13 UTC, crebollarramirez requested changes

2024-12-27 08:13 UTC, crebollarramirez commented on client/next.config.ts
Why did we need to make this change?

2024-12-27 23:36 UTC, OrigamiStarz commented on client/next.config.ts
I originally made the change as a temporary measure when testing the cards (since I used URLs that didn't align with the original remote pattern), should I change it back?

2024-12-28 02:58 UTC, crebollarramirez commented on client/next.config.ts
Since it was used for testing purposes, I think changing it back would be wise so we wouldnt run into issues in the future.

2024-12-28 03:01 UTC, crebollarramirez commented on client/next.config.ts
I just used git checkout to test the commit that has that temporary change for testing.

2024-12-28 03:04 UTC, crebollarramirez commented
Everything looks awesome, there is just one more thing, I'm sorry. When I tested it out, the dislike and like buttons are too low, are you able to make them closer to the swipe posts? After that, everything is good to merge.
![Posts View](https://github.com/user-attachments/assets/8d4d9322-4cfd-49ab-99ee-35e27169f69e)

2024-12-28 03:52 UTC, crebollarramirez approved these changes

2024-12-28 03:52 UTC, merged